### ISSUE TITLE
Change repo topic from "crystal-lang" to "crystal"

### ISSUE THREAD

**Issue by matiasgarciaisaia** [charly-lang/charly#158]
The community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

Currently, charly is [the only repo with `crystal-lang` topic](https://github.com/search?utf8=✓&q=topic%3Acrystal-lang&type=Repositories).

It would be nice to converge in `crystal`, so we avoid fragmentation in the community.

Thanks :)

**Comment by KCreate** [comment]
Alright, just changed it :)
